[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window]
opacity = 1
dynamic_title = true
option_as_alt = "OnlyLeft" # or "Both"

[scrolling]
history = 10000
multiplier = 3

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.normal]
family = "SF Mono"
style = "Regular"

[font.bold]
family = "SF Mono"
style = "Bold"

[font.italic]
family = "SF Mono"
style = "Italic"

[font.bold_italic]
family = "SF Mono"
style = "Bold Italic"

[terminal]
osc52 = "CopyPaste"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.3
blink_interval = 1000
blink_timeout = 10

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
    { key = "Return", mods = "Shift", chars = "\n" },
    { key = "Right",  mods = "Alt", chars = "\u001bF" },
    { key = "Left",   mods = "Alt", chars = "\u001bB" },
    { key = "Space",  mods = "Alt|Shift", action = "ToggleViMode" },
]
