[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window]
opacity = 1
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "SF Mono"
style = "Regular"

[selection]
save_to_clipboard = true

